server:
  port: 8082
  
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/orderdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: ${DB_USER:root}
#    password: ${DB_PASS:ownermysql001}
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      #host: localhost         # luego pondremos docker/k8s
      #port: 27017
      #database: orderdb
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always