server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  security:
    user:
      name: ${CONFIG_USER:config}
      password: ${CONFIG_PASS:config123}
  cloud:
    config:
      server:
        native:
          search-locations: file:../config-repo
management:
  endpoints:
    web:
      exposure:
        include: health,info,env

logging:
  level:
    org.springframework.cloud.config.server: DEBUG